//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("AttributeList", Namespace="", IsNullable=false)]
public partial class AttributeList_T {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BooleanAttribute", typeof(BooleanAttribute_T))]
    [System.Xml.Serialization.XmlElementAttribute("DateAttribute", typeof(DateAttribute_T))]
    [System.Xml.Serialization.XmlElementAttribute("IntegerAttribute", typeof(IntegerAttribute_T))]
    [System.Xml.Serialization.XmlElementAttribute("RealAttribute", typeof(RealAttribute_T))]
    [System.Xml.Serialization.XmlElementAttribute("StringAttribute", typeof(StringAttribute_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("BooleanAttribute", Namespace="", IsNullable=false)]
public partial class BooleanAttribute_T {
    
    private string nameField;
    
    private bool informativeField;
    
    private bool systemDefinedField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private bool valueField;
    
    public BooleanAttribute_T() {
        this.informativeField = false;
        this.systemDefinedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool SystemDefined {
        get {
            return this.systemDefinedField;
        }
        set {
            this.systemDefinedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public bool Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("DateAttribute", Namespace="", IsNullable=false)]
public partial class DateAttribute_T {
    
    private string nameField;
    
    private bool informativeField;
    
    private bool systemDefinedField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private System.DateTime valueField;
    
    public DateAttribute_T() {
        this.informativeField = false;
        this.systemDefinedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool SystemDefined {
        get {
            return this.systemDefinedField;
        }
        set {
            this.systemDefinedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("IntegerAttribute", Namespace="", IsNullable=false)]
public partial class IntegerAttribute_T {
    
    private string nameField;
    
    private bool informativeField;
    
    private bool systemDefinedField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private string valueField;
    
    public IntegerAttribute_T() {
        this.informativeField = false;
        this.systemDefinedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool SystemDefined {
        get {
            return this.systemDefinedField;
        }
        set {
            this.systemDefinedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("RealAttribute", Namespace="", IsNullable=false)]
public partial class RealAttribute_T {
    
    private string nameField;
    
    private bool informativeField;
    
    private bool systemDefinedField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private double valueField;
    
    public RealAttribute_T() {
        this.informativeField = false;
        this.systemDefinedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool SystemDefined {
        get {
            return this.systemDefinedField;
        }
        set {
            this.systemDefinedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("StringAttribute", Namespace="", IsNullable=false)]
public partial class StringAttribute_T {
    
    private string nameField;
    
    private bool informativeField;
    
    private bool systemDefinedField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private string valueField;
    
    public StringAttribute_T() {
        this.informativeField = false;
        this.systemDefinedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool SystemDefined {
        get {
            return this.systemDefinedField;
        }
        set {
            this.systemDefinedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Blank", Namespace="", IsNullable=false)]
public partial class Blank_T {
    
    private string numField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    public Blank_T() {
        this.numField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string Num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Comment", Namespace="", IsNullable=false)]
public partial class Comment_T {
    
    private IntegerAttribute_T integerAttributeField;
    
    private MultiLanguageText_T[] multiLanguageTextField;
    
    private bool insertedField;
    
    private bool informativeField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    public Comment_T() {
        this.insertedField = false;
        this.informativeField = false;
    }
    
    /// <remarks/>
    public IntegerAttribute_T IntegerAttribute {
        get {
            return this.integerAttributeField;
        }
        set {
            this.integerAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MultiLanguageText")]
    public MultiLanguageText_T[] MultiLanguageText {
        get {
            return this.multiLanguageTextField;
        }
        set {
            this.multiLanguageTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Inserted {
        get {
            return this.insertedField;
        }
        set {
            this.insertedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("MultiLanguageText", Namespace="", IsNullable=false)]
public partial class MultiLanguageText_T {
    
    private string langField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("LineComment", Namespace="", IsNullable=false)]
public partial class LineComment_T {
    
    private IntegerAttribute_T integerAttributeField;
    
    private object[] itemsField;
    
    private bool insertedField;
    
    private bool noClosingBracketField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    public LineComment_T() {
        this.insertedField = false;
        this.noClosingBracketField = false;
    }
    
    /// <remarks/>
    public IntegerAttribute_T IntegerAttribute {
        get {
            return this.integerAttributeField;
        }
        set {
            this.integerAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("Text", typeof(Text_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Inserted {
        get {
            return this.insertedField;
        }
        set {
            this.insertedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool NoClosingBracket {
        get {
            return this.noClosingBracketField;
        }
        set {
            this.noClosingBracketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Text", Namespace="", IsNullable=false)]
public partial class Text_T {
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("NewLine", Namespace="", IsNullable=false)]
public partial class NewLine_T {
    
    private string numField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    public NewLine_T() {
        this.numField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string Num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Token", Namespace="", IsNullable=false)]
public partial class Token_T {
    
    private IntegerAttribute_T integerAttributeField;
    
    private string textField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    /// <remarks/>
    public IntegerAttribute_T IntegerAttribute {
        get {
            return this.integerAttributeField;
        }
        set {
            this.integerAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("ViewInfo", Namespace="", IsNullable=false)]
public partial class ViewInfo_T {
    
    private bool startField;
    
    private bool startFieldSpecified;
    
    private int xPosField;
    
    private bool xPosFieldSpecified;
    
    private int yPosField;
    
    private bool yPosFieldSpecified;
    
    private int widthField;
    
    private bool widthFieldSpecified;
    
    private int heightField;
    
    private bool heightFieldSpecified;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartSpecified {
        get {
            return this.startFieldSpecified;
        }
        set {
            this.startFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int XPos {
        get {
            return this.xPosField;
        }
        set {
            this.xPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XPosSpecified {
        get {
            return this.xPosFieldSpecified;
        }
        set {
            this.xPosFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int YPos {
        get {
            return this.yPosField;
        }
        set {
            this.yPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool YPosSpecified {
        get {
            return this.yPosFieldSpecified;
        }
        set {
            this.yPosFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WidthSpecified {
        get {
            return this.widthFieldSpecified;
        }
        set {
            this.widthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HeightSpecified {
        get {
            return this.heightFieldSpecified;
        }
        set {
            this.heightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("AbsoluteOffset", Namespace="", IsNullable=false)]
public partial class AbsoluteOffset_T {
    
    private int bitOffsetField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int BitOffset {
        get {
            return this.bitOffsetField;
        }
        set {
            this.bitOffsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Access", Namespace="", IsNullable=false)]
public partial class Access_T {
    
    private IntegerAttribute_T integerAttributeField;
    
    private object itemField;
    
    private object[] itemsField;
    
    private Scope_TE scopeField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    /// <remarks/>
    public IntegerAttribute_T IntegerAttribute {
        get {
            return this.integerAttributeField;
        }
        set {
            this.integerAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Address", typeof(Address_T))]
    [System.Xml.Serialization.XmlElementAttribute("CallInfo", typeof(CallInfo_T))]
    [System.Xml.Serialization.XmlElementAttribute("Constant", typeof(Constant_T))]
    [System.Xml.Serialization.XmlElementAttribute("DataType", typeof(DataType_T))]
    [System.Xml.Serialization.XmlElementAttribute("Expression", typeof(Expression_T))]
    [System.Xml.Serialization.XmlElementAttribute("Indirect", typeof(Indirect_T))]
    [System.Xml.Serialization.XmlElementAttribute("Instruction", typeof(Instruction_T))]
    [System.Xml.Serialization.XmlElementAttribute("Label", typeof(Label_T))]
    [System.Xml.Serialization.XmlElementAttribute("PredefinedVariable", typeof(PredefinedVariable_T))]
    [System.Xml.Serialization.XmlElementAttribute("Reference", typeof(Reference_T))]
    [System.Xml.Serialization.XmlElementAttribute("Statusword", typeof(Statusword_T))]
    [System.Xml.Serialization.XmlElementAttribute("Symbol", typeof(Symbol_T))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Scope_TE Scope {
        get {
            return this.scopeField;
        }
        set {
            this.scopeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Address", Namespace="", IsNullable=false)]
public partial class Address_T {
    
    private BooleanAttribute_T[] itemsField;
    
    private Area_TE areaField;
    
    private string typeField;
    
    private int blockNumberField;
    
    private bool blockNumberFieldSpecified;
    
    private int bitOffsetField;
    
    private bool bitOffsetFieldSpecified;
    
    private bool informativeField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    public Address_T() {
        this.informativeField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BooleanAttribute")]
    public BooleanAttribute_T[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Area_TE Area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int BlockNumber {
        get {
            return this.blockNumberField;
        }
        set {
            this.blockNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BlockNumberSpecified {
        get {
            return this.blockNumberFieldSpecified;
        }
        set {
            this.blockNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int BitOffset {
        get {
            return this.bitOffsetField;
        }
        set {
            this.bitOffsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BitOffsetSpecified {
        get {
            return this.bitOffsetFieldSpecified;
        }
        set {
            this.bitOffsetFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum Area_TE {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    PeripheryInput,
    
    /// <remarks/>
    PeripheryOutput,
    
    /// <remarks/>
    Input,
    
    /// <remarks/>
    Output,
    
    /// <remarks/>
    Memory,
    
    /// <remarks/>
    FB,
    
    /// <remarks/>
    FC,
    
    /// <remarks/>
    DB,
    
    /// <remarks/>
    DI,
    
    /// <remarks/>
    Timer,
    
    /// <remarks/>
    Counter,
    
    /// <remarks/>
    Local,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("CallInfo", Namespace="", IsNullable=false)]
public partial class CallInfo_T {
    
    private object[] itemsField;
    
    private string nameField;
    
    private BlockType_TE blockTypeField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("DateAttribute", typeof(DateAttribute_T))]
    [System.Xml.Serialization.XmlElementAttribute("Instance", typeof(Instance_T))]
    [System.Xml.Serialization.XmlElementAttribute("IntegerAttribute", typeof(IntegerAttribute_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NamelessParameter", typeof(NamelessParameter_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    [System.Xml.Serialization.XmlElementAttribute("Parameter", typeof(Parameter_T))]
    [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BlockType_TE BlockType {
        get {
            return this.blockTypeField;
        }
        set {
            this.blockTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Instance", Namespace="", IsNullable=false)]
public partial class Instance_T {
    
    private object[] itemsField;
    
    private object[] items1Field;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private Scope_TE scopeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AbsoluteOffset", typeof(AbsoluteOffset_T))]
    [System.Xml.Serialization.XmlElementAttribute("Address", typeof(Address_T))]
    [System.Xml.Serialization.XmlElementAttribute("Component", typeof(Component_T))]
    [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    public object[] Items1 {
        get {
            return this.items1Field;
        }
        set {
            this.items1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Scope_TE Scope {
        get {
            return this.scopeField;
        }
        set {
            this.scopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Component", Namespace="", IsNullable=false)]
public partial class Component_T {
    
    private object[] itemsField;
    
    private string nameField;
    
    private string sliceAccessModifierField;
    
    private string simpleAccessModifierField;
    
    private AccessModifier_TE accessModifierField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    public Component_T() {
        this.sliceAccessModifierField = "undef";
        this.simpleAccessModifierField = "None";
        this.accessModifierField = AccessModifier_TE.None;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Access", typeof(Access_T))]
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("BooleanAttribute", typeof(BooleanAttribute_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("undef")]
    public string SliceAccessModifier {
        get {
            return this.sliceAccessModifierField;
        }
        set {
            this.sliceAccessModifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("None")]
    public string SimpleAccessModifier {
        get {
            return this.simpleAccessModifierField;
        }
        set {
            this.simpleAccessModifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(AccessModifier_TE.None)]
    public AccessModifier_TE AccessModifier {
        get {
            return this.accessModifierField;
        }
        set {
            this.accessModifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum AccessModifier_TE {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    Array,
    
    /// <remarks/>
    Reference,
    
    /// <remarks/>
    ReferenceToArray,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum Scope_TE {
    
    /// <remarks/>
    Undef,
    
    /// <remarks/>
    GlobalConstant,
    
    /// <remarks/>
    LocalConstant,
    
    /// <remarks/>
    GlobalVariable,
    
    /// <remarks/>
    LocalVariable,
    
    /// <remarks/>
    Instruction,
    
    /// <remarks/>
    Label,
    
    /// <remarks/>
    TypedConstant,
    
    /// <remarks/>
    AddressConstant,
    
    /// <remarks/>
    LiteralConstant,
    
    /// <remarks/>
    AlarmConstant,
    
    /// <remarks/>
    Address,
    
    /// <remarks/>
    Statusword,
    
    /// <remarks/>
    Expression,
    
    /// <remarks/>
    Unnamed,
    
    /// <remarks/>
    Call,
    
    /// <remarks/>
    CallWithType,
    
    /// <remarks/>
    UserType,
    
    /// <remarks/>
    SystemType,
    
    /// <remarks/>
    Reference,
    
    /// <remarks/>
    PredefinedVariable,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("NamelessParameter", Namespace="", IsNullable=false)]
public partial class NamelessParameter_T {
    
    private StringAttribute_T[] stringAttributeField;
    
    private object[] itemsField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StringAttribute")]
    public StringAttribute_T[] StringAttribute {
        get {
            return this.stringAttributeField;
        }
        set {
            this.stringAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Access", typeof(Access_T))]
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Parameter", Namespace="", IsNullable=false)]
public partial class Parameter_T {
    
    private IntegerAttribute_T integerAttributeField;
    
    private StringAttribute_T stringAttributeField;
    
    private BooleanAttribute_T[] booleanAttributeField;
    
    private object[] itemsField;
    
    private string nameField;
    
    private SectionName_TE sectionField;
    
    private bool sectionFieldSpecified;
    
    private string typeField;
    
    private string templateReferenceField;
    
    private bool informativeField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    public Parameter_T() {
        this.informativeField = false;
    }
    
    /// <remarks/>
    public IntegerAttribute_T IntegerAttribute {
        get {
            return this.integerAttributeField;
        }
        set {
            this.integerAttributeField = value;
        }
    }
    
    /// <remarks/>
    public StringAttribute_T StringAttribute {
        get {
            return this.stringAttributeField;
        }
        set {
            this.stringAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BooleanAttribute")]
    public BooleanAttribute_T[] BooleanAttribute {
        get {
            return this.booleanAttributeField;
        }
        set {
            this.booleanAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Access", typeof(Access_T))]
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SectionName_TE Section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SectionSpecified {
        get {
            return this.sectionFieldSpecified;
        }
        set {
            this.sectionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TemplateReference {
        get {
            return this.templateReferenceField;
        }
        set {
            this.templateReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum SectionName_TE {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    Input,
    
    /// <remarks/>
    Return,
    
    /// <remarks/>
    Output,
    
    /// <remarks/>
    InOut,
    
    /// <remarks/>
    Static,
    
    /// <remarks/>
    Temp,
    
    /// <remarks/>
    Constant,
    
    /// <remarks/>
    Base,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum BlockType_TE {
    
    /// <remarks/>
    DB,
    
    /// <remarks/>
    FB,
    
    /// <remarks/>
    FC,
    
    /// <remarks/>
    OB,
    
    /// <remarks/>
    UDT,
    
    /// <remarks/>
    FBT,
    
    /// <remarks/>
    FCT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Constant", Namespace="", IsNullable=false)]
public partial class Constant_T {
    
    private ConstantType_T constantTypeField;
    
    private ConstantValue_T constantValueField;
    
    private StringAttribute_T[] stringAttributeField;
    
    private BooleanAttribute_T[] booleanAttributeField;
    
    private string nameField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    /// <remarks/>
    public ConstantType_T ConstantType {
        get {
            return this.constantTypeField;
        }
        set {
            this.constantTypeField = value;
        }
    }
    
    /// <remarks/>
    public ConstantValue_T ConstantValue {
        get {
            return this.constantValueField;
        }
        set {
            this.constantValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StringAttribute")]
    public StringAttribute_T[] StringAttribute {
        get {
            return this.stringAttributeField;
        }
        set {
            this.stringAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BooleanAttribute")]
    public BooleanAttribute_T[] BooleanAttribute {
        get {
            return this.booleanAttributeField;
        }
        set {
            this.booleanAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("ConstantType", Namespace="", IsNullable=false)]
public partial class ConstantType_T {
    
    private bool informativeField;
    
    private bool informativeFieldSpecified;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InformativeSpecified {
        get {
            return this.informativeFieldSpecified;
        }
        set {
            this.informativeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("ConstantValue", Namespace="", IsNullable=false)]
public partial class ConstantValue_T {
    
    private bool informativeField;
    
    private bool informativeFieldSpecified;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InformativeSpecified {
        get {
            return this.informativeFieldSpecified;
        }
        set {
            this.informativeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("DataType", Namespace="", IsNullable=false)]
public partial class DataType_T {
    
    private bool informativeField;
    
    private bool informativeFieldSpecified;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InformativeSpecified {
        get {
            return this.informativeFieldSpecified;
        }
        set {
            this.informativeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Expression", Namespace="", IsNullable=false)]
public partial class Expression_T {
    
    private object[] itemsField;
    
    private object[] items1Field;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Access", typeof(Access_T))]
    [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    public object[] Items1 {
        get {
            return this.items1Field;
        }
        set {
            this.items1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Indirect", Namespace="", IsNullable=false)]
public partial class Indirect_T {
    
    private object[] itemsField;
    
    private Access_T accessField;
    
    private Width_TE widthField;
    
    private Area_TE areaField;
    
    private bool areaFieldSpecified;
    
    private Register_TE registerField;
    
    private bool registerFieldSpecified;
    
    private string bitOffsetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    public Access_T Access {
        get {
            return this.accessField;
        }
        set {
            this.accessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Width_TE Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Area_TE Area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AreaSpecified {
        get {
            return this.areaFieldSpecified;
        }
        set {
            this.areaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Register_TE Register {
        get {
            return this.registerField;
        }
        set {
            this.registerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RegisterSpecified {
        get {
            return this.registerFieldSpecified;
        }
        set {
            this.registerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BitOffset {
        get {
            return this.bitOffsetField;
        }
        set {
            this.bitOffsetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum Width_TE {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    Bit,
    
    /// <remarks/>
    Byte,
    
    /// <remarks/>
    Word,
    
    /// <remarks/>
    Offset,
    
    /// <remarks/>
    Double,
    
    /// <remarks/>
    Pointer,
    
    /// <remarks/>
    Long,
    
    /// <remarks/>
    Any,
    
    /// <remarks/>
    Block,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum Register_TE {
    
    /// <remarks/>
    AR1,
    
    /// <remarks/>
    AR2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Instruction", Namespace="", IsNullable=false)]
public partial class Instruction_T {
    
    private object[] itemsField;
    
    private string nameField;
    
    private string versionField;
    
    private bool informativeField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    public Instruction_T() {
        this.informativeField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("Instance", typeof(Instance_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NamelessParameter", typeof(NamelessParameter_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    [System.Xml.Serialization.XmlElementAttribute("Parameter", typeof(Parameter_T))]
    [System.Xml.Serialization.XmlElementAttribute("TemplateValue", typeof(TemplateValue_T))]
    [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Informative {
        get {
            return this.informativeField;
        }
        set {
            this.informativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("TemplateValue", Namespace="", IsNullable=false)]
public partial class TemplateValue_T {
    
    private string nameField;
    
    private TemplateType_TE typeField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TemplateType_TE Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum TemplateType_TE {
    
    /// <remarks/>
    Cardinality,
    
    /// <remarks/>
    Type,
    
    /// <remarks/>
    Operation,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Label", Namespace="", IsNullable=false)]
public partial class Label_T {
    
    private BooleanAttribute_T booleanAttributeField;
    
    private object[] itemsField;
    
    private Token_T tokenField;
    
    private string nameField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    /// <remarks/>
    public BooleanAttribute_T BooleanAttribute {
        get {
            return this.booleanAttributeField;
        }
        set {
            this.booleanAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    public Token_T Token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("PredefinedVariable", Namespace="", IsNullable=false)]
public partial class PredefinedVariable_T {
    
    private PredefinedVariable_TE nameField;
    
    private int uIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PredefinedVariable_TE Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum PredefinedVariable_TE {
    
    /// <remarks/>
    ENO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Reference", Namespace="", IsNullable=false)]
public partial class Reference_T {
    
    private object[] itemsField;
    
    private Token_T tokenField;
    
    private object[] items1Field;
    
    private Access_T accessField;
    
    private object[] items2Field;
    
    private Token_T token1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T), Order=0)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public Token_T Token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T), Order=2)]
    public object[] Items1 {
        get {
            return this.items1Field;
        }
        set {
            this.items1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public Access_T Access {
        get {
            return this.accessField;
        }
        set {
            this.accessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T), Order=4)]
    public object[] Items2 {
        get {
            return this.items2Field;
        }
        set {
            this.items2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Token", Order=5)]
    public Token_T Token1 {
        get {
            return this.token1Field;
        }
        set {
            this.token1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Statusword", Namespace="", IsNullable=false)]
public partial class Statusword_T {
    
    private Statusword_TE combinationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Statusword_TE Combination {
        get {
            return this.combinationField;
        }
        set {
            this.combinationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum Statusword_TE {
    
    /// <remarks/>
    BR,
    
    /// <remarks/>
    OV,
    
    /// <remarks/>
    OS,
    
    /// <remarks/>
    EQ,
    
    /// <remarks/>
    NE,
    
    /// <remarks/>
    GT,
    
    /// <remarks/>
    LT,
    
    /// <remarks/>
    GE,
    
    /// <remarks/>
    LE,
    
    /// <remarks/>
    UO,
    
    /// <remarks/>
    NU,
    
    /// <remarks/>
    STW,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Symbol", Namespace="", IsNullable=false)]
public partial class Symbol_T {
    
    private object[] itemsField;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    private Scope_TE scopeField;
    
    private bool scopeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AbsoluteOffset", typeof(AbsoluteOffset_T))]
    [System.Xml.Serialization.XmlElementAttribute("Access", typeof(Access_T))]
    [System.Xml.Serialization.XmlElementAttribute("Address", typeof(Address_T))]
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T))]
    [System.Xml.Serialization.XmlElementAttribute("Component", typeof(Component_T))]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T))]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T))]
    [System.Xml.Serialization.XmlElementAttribute("Token", typeof(Token_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Scope_TE Scope {
        get {
            return this.scopeField;
        }
        set {
            this.scopeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ScopeSpecified {
        get {
            return this.scopeFieldSpecified;
        }
        set {
            this.scopeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("LabelDeclaration", Namespace="", IsNullable=false)]
public partial class LabelDeclaration_T {
    
    private IntegerAttribute_T integerAttributeField;
    
    private Label_T labelField;
    
    private object[] itemsField;
    
    private Token_T tokenField;
    
    private object[] items1Field;
    
    private int uIdField;
    
    private bool uIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public IntegerAttribute_T IntegerAttribute {
        get {
            return this.integerAttributeField;
        }
        set {
            this.integerAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public Label_T Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T), Order=2)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public Token_T Token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Blank", typeof(Blank_T), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(Comment_T), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("LineComment", typeof(LineComment_T), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("NewLine", typeof(NewLine_T), Order=4)]
    public object[] Items1 {
        get {
            return this.items1Field;
        }
        set {
            this.items1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UIdSpecified {
        get {
            return this.uIdFieldSpecified;
        }
        set {
            this.uIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Powerrail", Namespace="", IsNullable=false)]
public partial class Powerrail_T {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Openbranch", Namespace="", IsNullable=false)]
public partial class Openbranch_T {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("OpenCon", Namespace="", IsNullable=false)]
public partial class OpenCon_T {
    
    private int uIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Call", Namespace="", IsNullable=false)]
public partial class Call_T {
    
    private CallInfo_T callInfoField;
    
    private TemplateValue_T[] templateValueField;
    
    private AutomaticTyped_T[] automaticTypedField;
    
    private Invisible_T[] invisibleField;
    
    private Neg_T[] negatedField;
    
    private Comment_T commentField;
    
    private int uIdField;
    
    /// <remarks/>
    public CallInfo_T CallInfo {
        get {
            return this.callInfoField;
        }
        set {
            this.callInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TemplateValue")]
    public TemplateValue_T[] TemplateValue {
        get {
            return this.templateValueField;
        }
        set {
            this.templateValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AutomaticTyped")]
    public AutomaticTyped_T[] AutomaticTyped {
        get {
            return this.automaticTypedField;
        }
        set {
            this.automaticTypedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Invisible")]
    public Invisible_T[] Invisible {
        get {
            return this.invisibleField;
        }
        set {
            this.invisibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Negated")]
    public Neg_T[] Negated {
        get {
            return this.negatedField;
        }
        set {
            this.negatedField = value;
        }
    }
    
    /// <remarks/>
    public Comment_T Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("AutomaticTyped", Namespace="", IsNullable=false)]
public partial class AutomaticTyped_T {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Invisible", Namespace="", IsNullable=false)]
public partial class Invisible_T {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Negated", Namespace="", IsNullable=false)]
public partial class Neg_T {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("FlgNet", Namespace="", IsNullable=false)]
public partial class FlgNet_T {
    
    private Labels_T labelsField;
    
    private object[] partsField;
    
    private Wires_T wiresField;
    
    /// <remarks/>
    public Labels_T Labels {
        get {
            return this.labelsField;
        }
        set {
            this.labelsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Access", typeof(Access_T), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Call", typeof(Call_T), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Part", typeof(Part_T), IsNullable=false)]
    public object[] Parts {
        get {
            return this.partsField;
        }
        set {
            this.partsField = value;
        }
    }
    
    /// <remarks/>
    public Wires_T Wires {
        get {
            return this.wiresField;
        }
        set {
            this.wiresField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Labels", Namespace="", IsNullable=false)]
public partial class Labels_T {
    
    private LabelDeclaration_T[] labelDeclarationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LabelDeclaration")]
    public LabelDeclaration_T[] LabelDeclaration {
        get {
            return this.labelDeclarationField;
        }
        set {
            this.labelDeclarationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Part", Namespace="", IsNullable=false)]
public partial class Part_T {
    
    private object itemField;
    
    private TemplateValue_T[] templateValueField;
    
    private AutomaticTyped_T[] automaticTypedField;
    
    private Invisible_T[] invisibleField;
    
    private Neg_T[] negatedField;
    
    private Comment_T commentField;
    
    private int uIdField;
    
    private string nameField;
    
    private string versionField;
    
    private bool disabledENOField;
    
    public Part_T() {
        this.disabledENOField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Equation", typeof(Equation_T))]
    [System.Xml.Serialization.XmlElementAttribute("Instance", typeof(Instance_T))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TemplateValue")]
    public TemplateValue_T[] TemplateValue {
        get {
            return this.templateValueField;
        }
        set {
            this.templateValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AutomaticTyped")]
    public AutomaticTyped_T[] AutomaticTyped {
        get {
            return this.automaticTypedField;
        }
        set {
            this.automaticTypedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Invisible")]
    public Invisible_T[] Invisible {
        get {
            return this.invisibleField;
        }
        set {
            this.invisibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Negated")]
    public Neg_T[] Negated {
        get {
            return this.negatedField;
        }
        set {
            this.negatedField = value;
        }
    }
    
    /// <remarks/>
    public Comment_T Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool DisabledENO {
        get {
            return this.disabledENOField;
        }
        set {
            this.disabledENOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Equation", Namespace="", IsNullable=false)]
public partial class Equation_T {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Wires", Namespace="", IsNullable=false)]
public partial class Wires_T {
    
    private Wire_T[] wireField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Wire")]
    public Wire_T[] Wire {
        get {
            return this.wireField;
        }
        set {
            this.wireField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Wire", Namespace="", IsNullable=false)]
public partial class Wire_T {
    
    private object[] itemsField;
    
    private int uIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IdentCon", typeof(IdentCon_T))]
    [System.Xml.Serialization.XmlElementAttribute("NameCon", typeof(NameCon_T))]
    [System.Xml.Serialization.XmlElementAttribute("OpenCon", typeof(OpenCon_T))]
    [System.Xml.Serialization.XmlElementAttribute("Openbranch", typeof(Openbranch_T))]
    [System.Xml.Serialization.XmlElementAttribute("Powerrail", typeof(Powerrail_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("IdentCon", Namespace="", IsNullable=false)]
public partial class IdentCon_T {
    
    private int uIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("NameCon", Namespace="", IsNullable=false)]
public partial class NameCon_T {
    
    private int uIdField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int UId {
        get {
            return this.uIdField;
        }
        set {
            this.uIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Parts", Namespace="", IsNullable=false)]
public partial class Parts_T {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Access", typeof(Access_T))]
    [System.Xml.Serialization.XmlElementAttribute("Call", typeof(Call_T))]
    [System.Xml.Serialization.XmlElementAttribute("Part", typeof(Part_T))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
